### PR TITLE
Silent PushWoosh Notifications for iOS

### PR DESCRIPTION
**Pull request by akodkod**
Hi!

For sending silent pushes need to send empty content to PushWoosh API. But now we get Exception if we send empty content. Please, merge my changes and bump gem version. Also need to update README file.

Thank you,
Andrew

### CODE REVIEW

**Comment by MrWEST** [comment]
Tests was updated.

**Comment by pedroandrade** [comment]
Hi @MrWEST, 

Thanks for this PR, but... could you fix the specs?

**Comment by antillas21** [comment]
@MrWEST I'm missing the point in re-writing almost all files just to replace double-quotes by single-quotes (and other personal code styling) to add this feature.

After looking at this PR, the only significant change I can see is in the `lib/pushwoosh/push_notification.rb` file.

IMHO a PR should fix bugs, add/remove features and leave code style decisions to the gem maintainer, this will allow PRs code to be specific to the issue being addressed.

Thoughts @MrWEST and @pedroandrade ?

**Comment by MrWEST** [comment]
@antillas21, yeah, I agree with you, but in some files we have a different code style. I think need to fix it, I'll create another PR for this and we discuss it there.

@pedroandrade, okay, no problem, I'll update specs soon.

**Pull request closed without merging**
